### ISSUE TITLE
issue with sensor and card 

### ISSUE THREAD

**Issue by Drwarfare** [PiotrMachowski/Home-Assistant-custom-components-Google-Keep#17]
I currently have it set up in my sensors folder as such 
```
- platform: google_keep
  username: XXXXXXX@gmail.com
  password: XXXXXXX
  titles:
    - 'Home Assistant'
    - 'Test'
    - 'Shopping List'
  pinned: true
```

is this correct as when i use the card it just says that it is no notes found

many thanks

Drwarfare
